apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: h8o62oddc-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: h8o62oddc-go 
  name: h8o62oddc-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: h8o62oddc-go 
